<a href="https://colab.research.google.com/github/muneeb1505/DSA-IMP-Questions-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## 1 Dimensional array


In [6]:
a = np.array([10, 20, 30])
print(a)

# Get dimension
print(a.ndim)

[10 20 30]
1


## 2 dimension array

In [9]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

# Get shape of array
print(b.shape) # prints 2 , 3 -> 2 rows and 3 columns

[[9. 8. 7.]
 [6. 5. 4.]]
(2, 3)


In [12]:
# Get type
a.dtype

dtype('int64')

In [13]:
# Get size
a.itemsize

8

## Accessing/Changing specific elements, rows, columns,etc

In [38]:
nums = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(nums)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element [r, c], r -> row, c -> col
print(nums[1, 5]) # It returns 13

13


In [21]:
# Get a specific row
nums[0, :] # 0 -> row 0, : -> get all columns from row 0

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a specific column
nums[:, 3] # -> : -> every row, column 3 -> [4, 11]

array([ 4, 11])

In [27]:
# [startIndex: endIndex: stepSize]
nums[0, 1:6:2] # At row 0, Get elements from 1st col upto 6th col (6 is not included) with 2 steps/jumps -> [2, 4, 6]

array([2, 4, 6])

In [39]:
# Update a element
nums[0, 6] = 15
nums

array([[ 1,  2,  3,  4,  5,  6, 15],
       [ 8,  9, 10, 11, 12, 13, 14]])

## 3D dimension array

In [42]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)

a.shape # (2, 2, 2) -> (number of tables/arrays, rows, columns)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [45]:
# Get a specific element, Syntax: a[table, row, column]
a[1, 0, 1]

a[:, 1, :] # 1. Get all tables/arrays, 2. get 1st row , 3. all columns from 1st row

array([[3, 4],
       [7, 8]])

## Initializing Different Types of Arrays

In [47]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
# All 1s matrix
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
# Any other number
np.full((2, 2), 60) # 2 parameters: 1) shape ex: 2,2  2) value you want ex:60,70,etc

array([[60, 60],
       [60, 60]])

In [50]:
# You give NumPy an existing array, and it copies its shape.
np.full_like(nums, 10) # Make an array the same shape as nums, and fill it with 10.

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [62]:
# Random decimal numbers
np.random.rand(4, 2)

# Random integer number
num = np.random.randint(10) # Returns a random number between 0 and 9 inclusive
print(num)

6


In [52]:
np. random.random_sample(nums.shape) # generate random decimal numbers array of same shape as 'nums'.

array([[0.69296227, 0.08390676, 0.04412392, 0.79431946, 0.10505407,
        0.82365244, 0.1273526 ],
       [0.86470187, 0.93253223, 0.25662326, 0.81798696, 0.33474975,
        0.4726378 , 0.6485554 ]])

## Problems on Numpy

In [89]:
# Step 1
arr_ones = np.ones((5, 5))
print(arr_ones)

# Step 2
arr_zeroes = np.zeros((3, 3))
arr_zeroes[1, 1] = 9
print(arr_zeroes)

# Step 3
arr_ones[1:4, 1:4] = arr_zeroes
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Mathematics

In [94]:
a = np.array([1, 2, 3, 4, 5])
print(a)

squares_arr = a ** 2
print(squares_arr)

[1 2 3 4 5]
[ 1  4  9 16 25]
